### ISSUE TITLE
评论开启了似乎没用呃？

### ISSUE THREAD

**Issue by memoiry** [zhengxiaowai/hexo-theme-lessless#2]
谢谢分享~非常棒的主题！

想问下我把 disqus enable 了后，好像没有看到评论区开启呀？还需要改哪里吗？谢谢

**Comment by zhengxiaowai** [comment]
@memoiry disqus 被墙了，没开翻墙是看不到的。。。

**Comment by memoiry** [comment]
emmm.. 谢啦，似乎是 shortname 的问题。

刚才找了个[教程](http://www.jianshu.com/p/d68de067ea74?open_source=weibo_search)，登录 disqus 配置了下网站生成 shortname 替换后成功了，建议在 README 里指出~
